[project]
name = "animal-log"
version = "0.1.0"
description = ""
authors = [
    {name = "Ricardo Sans"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "passlib (>=1.7.4,<2.0.0)",
    "bcrypt (==3.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
